### PR TITLE
Update build description

### PR DESCRIPTION
**Pull request by gwolf2u**
update for INTL version and Android 7.0

### CODE REVIEW

**Comment by Kinglilrowrow** [comment]
What build is the keys taken from?

**Comment by gwolf2u** [comment]
LGs nougat build v20A OPEN EU

**Comment by Kinglilrowrow** [comment]
Okay, just didn't wanna commit keys from a carrier variant as that can trip security on some mobile banking apps.

**Comment by gwolf2u** [comment]
hehe no prob... just noticed on my build from today that AIDA reports wrong tmo version 
and thought should update ;)
cleanup a bit ya know 👍

**Pull request merged**
